CREATE TABLE api_keys (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	key TEXT NOT NULL UNIQUE,
	permissions TEXT[],
	comments TEXT[],
	version INTEGER,
	status BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);